name: build ubuntu 24.04

on:
  pull_request:
    branches:
      - debug
      - master
  push:
    branches:
      - debug
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    environment: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update package list
        run:  sudo apt-get update
      - name: Install software-properties-common
        run: sudo apt-get install software-properties-common
      - name: Install clang compiler and tools
        run: |
          sudo apt-get -y install clang ccache cmake pkg-config curl wget
      - name: Install dependencies
        run: |
          sudo apt-get install -y \
              libc++-dev libomp-dev liblzma-dev libxml2-dev \
              libprotobuf-dev protobuf-compiler\
              libqt5remoteobjects5-bin libqt5quickwidgets5 \
              libqt5quickcontrols2-5 libqt5qmlmodels5 libqt5qml5 \
              libqt5positioning5 libqt5dbus5 libqt5remoteobjects5-dev \
              libqt5svg5-dev libqt5sensors5-dev \
              qttools5-dev qttools5-dev-tools qtdeclarative5-dev \
              qtquickcontrols2-5-dev qtmultimedia5-dev qtpositioning5-dev \
              qml-module-qtquick2 qml-module-qtgraphicaleffects \
              qml-module-qtquick-layouts qml-module-qtquick-controls2 \
              qml-module-qt-labs-settings \
              libreadline-dev

      - name: Fetch submodules
        run: git submodule init && git submodule update
      - name: Configure build
        run: |
          cmake -B build \
              -DBUILD_DEVICE_MOBILE=ON \
              -DBUILD_SIMULATOR=ON -DBUILD_SIMULATOR_WITH_READLINE=ON \
              -Wno-dev
      - name: Build OSMIN
        run:  cmake --build build --target osmin
      - name: Build SIMULATOR
        run:  cmake --build build --target simulator
      - name: Build OSMSCOUT IMPORT
        run:  cmake --build build --target Import
      - name: Build OSMSCOUT STYLE EDITOR
        run:  cmake --build build --target StyleEditor
      - name: Install
        run:  sudo cmake --install build

